name: Format and Test

on: [push]
jobs:
  prettier:
    name: Prettier format check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write **/*.{js,md,html,css}
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: tests
        run: npm run test
        
