name: Build and Depoloy

on:
  push:
    branches: [ master ]
jobs:
  build:
    - name: Build dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build Dependencies
        run: npm run-script build
      - name: Archibe production artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
    
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up node.js
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Download artifact
      - run:  actions/dowload-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
