name: Continous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node_version: 12
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run-script build
        
